script: |
  set -e

  cd ~

  rm -rf employee-management-system

  git clone https://github.com/patnamraveendra1-beep/employee-management-system.git
  cd employee-management-system

  sudo docker stop $(sudo docker ps -q) || true
  sudo docker rm $(sudo docker ps -aq) || true

  sudo docker build -t ems-backend .

  sudo docker run -d -p 5000:5000 \
    -e MONGO_URI="mongodb+srv://patnam:Raveendra123@cluster0.sjc81fp.mongodb.net/ems?retryWrites=true&w=majority&appName=Cluster0" \
    -e JWT_SECRET="ems_secret" \
    ems-backend